name: Integration Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  start_dbs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./integration_test
    steps:
      - name: Start DBs
        run: docker compose up -d

  integration_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./integration_test
    env:
      MYSQL_HOST: 127.0.0.1
      POSTGRES_HOST: 127.0.0.1
    strategy:
      matrix:
        adapter: ['mysql2', 'postgresql']
        gemfile: ['ar_6.1', 'ar_7.0', 'ar_7.1']
    steps:
      - uses: actions/checkout@v2
      - name: Run integration test
        run: BUNDLE_GEMFILE=gemfiles/${{ matrix.gemfile }}.gemfile bundle exec rspec spec/${{ matrix.adapter }}_spec.rb
