name: Integration Test

on:
  push:
    branches:
      - main
      - v1
  pull_request:
    branches:
      - main
      - v1

env:
  RUBY_VERSION: 3.3

jobs:
  mysql:
    continue-on-error: true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./integration_test
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
      MYSQL_HOST: 127.0.0.1
      POSTGRES_HOST: 127.0.0.1
      MSSQL_HOST: 127.0.0.1
    strategy:
      matrix:
        gemfile:
          - ar_7.1
          - ar_7.2
    steps:
      - uses: actions/checkout@v4
      - name: Start DB
        run: docker compose up -d
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Run bundle install
        run: bundle install
      - name: Run integration test
        run: bundle exec rspec
