name: Unit tests

on:
  push:
    branches:
      - main
      - v1
  pull_request:
    branches:
      - main
      - v1

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 3.2
          - 3.3
        gemfile:
          - ar_6.1
          - ar_7.0
          - ar_7.1
          - ar_7.2

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests with ${{ matrix.gemfile }}.gemfile on ruby-${{ matrix.ruby-version }}
      run: bundle exec rspec spec/*_spec.rb
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
